services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_net
    env_file:
      - "./.env"
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    volumes: 
      - db-volume:/var/lib/mysql
    networks:
      - inception_net
    env_file:
      - "./.env"
    secrets:
      - sql_credentials
      - wp_credentials

  redis:
    build: ./requirements/redis
    container_name: redis
    image: redis
    restart: always
    networks:
      - inception_net
    env_file:
      - "./.env"
    volumes:
      - wp-volume:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_net
    env_file:
      - "./.env"
    environment:
      - USERNAME=$USERNAME
    depends_on:
      - mariadb
      - redis
    secrets:
      - sql_credentials
      - wp_credentials
    
  ftp:
    build: ./requirements/ftp
    container_name: ftp
    image: ftp
    restart: always
    ports:
      - "20:20"
      - "21:21"
    volumes:
      - wp-volume:/var/www/html
    networks:
      - inception_net
    depends_on:
      - wordpress
    secrets:
      - ftp_credentials

volumes:
  wp-volume:
    driver_opts:
      type: none
      device: "$HOME/data/wp_data"
      o: bind
  db-volume:
    driver_opts:
      type: none
      device: "$HOME/data/db_data"
      o: bind

networks:
  inception_net:
    driver: bridge

secrets:
  sql_credentials:
    file: ../secrets/sql_credentials.txt
  wp_credentials:
    file: ../secrets/wp_credentials.txt
  ftp_credentials:
    file: ../secrets/ftp_credentials.txt